### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#4]
add some tests

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
> TypeError: resource.relationships.field_references.data.flatMap is not a function

      291 |                     resource.relationships.field_references.data.length > 0
      292 |             ) {
    > 293 |                     references = resource.relationships.field_references.data.flatMap((referenceReference) => {
          |                                  ^
      294 |                             let filteredReferences = referencesArray.filter((referenceObject) => {
      295 |                                     return (
      296 |                                             referenceReference.type === referenceObject.type &&

      at Object.extractReferencesfromResource (../csis-helpers-js/src/lib/CSISHelpers.js:293:17)
      at Object.extractReferencesfromResource (src/__tests__/CSISHelpers.test.js:111:36)

**Comment by p-a-s-c-a-l** [comment]
flatMap isn't supported by Node.js < version 10

**Comment by p-a-s-c-a-l** [comment]
Consider using `react-app-polyfill` instead of installing the lasted node version (also on CI!) as explained [here](https://stackoverflow.com/a/58159321).

**Comment by p-a-s-c-a-l** [comment]
>  Error: Cross origin http://localhost forbidden

**Comment by p-a-s-c-a-l** [comment]
Solution: 
`axios.defaults.adapter = require('axios/lib/adapters/http');`

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
Tests broke with absolutely unhelpful error message:

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "error caught in fetchData Error: connect EACCES 192.168.178.28:8118
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
```
