### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#9]
``
$ yarn run build
yarn run v1.19.1
$ rollup -c

src/index.js → dist/index.js, dist/index.es.js...
[!] (plugin babel) Error: Cannot find module './_baseToString'
src/index.js
Error: Cannot find module './_baseToString'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/docker/.cache/yarn/v6/.tmp/4ae158f9f1c6f799bb648d435768fc34.3033f70c462a618a6f24fa49d809e616db4c74ec.prepare/node_modules/lodash/toString.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

``

**Comment by p-a-s-c-a-l** [comment]
`` error https://registry.yarnpkg.com/resolve/-/resolve-1.12.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/home/docker/.cache/yarn/v6/npm-resolve-1.12.0-3fc644a35c84a48554609ff26ec52b66fa577df6-integrity/node_modules/resolve/test/resolver/same_names/foo.js'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
``

**Comment by p-a-s-c-a-l** [comment]
add `--network-concurrency 1` to `yarn install`

See https://github.com/yarnpkg/yarn/issues/2629#issuecomment-283580308

**Comment by p-a-s-c-a-l** [comment]
Again: 

>https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/home/docker/.cache/yarn/v6/npm-lodash-4.17.15-b447f6670a0455bbfeedd11392eff330ea097548-integrity/node_modules/lodash/_createFlow.js'"

**Comment by p-a-s-c-a-l** [comment]
this stuff is not ready for production use:

> Done in 4.11s.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || >=11.0.0". Got "8.10.0"
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
error json-server@0.16.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command
